// examples/react-todo/src/components/TodoFooter.tsx
import { useService, useServiceState } from "@separa/react";
import { TodoService, type TodoFilter } from "@separa/example-todo-shared";
import styles from "./TodoFooter.module.css";

const FILTERS: { label: string; value: TodoFilter }[] = [
  { label: "全部", value: "all" },
  { label: "待完成", value: "active" },
  { label: "已完成", value: "completed" },
];

/**
 * TodoFooter — 展示统计信息、筛选按钮与清除已完成操作。
 * 使用 useServiceState 分别订阅需要的字段，按需精细更新。
 */
export function TodoFooter() {
  const todo = useService(TodoService);
  const totalCount = useServiceState(TodoService, (s) => s.totalCount);
  const activeCount = useServiceState(TodoService, (s) => s.activeCount);
  const completedCount = useServiceState(TodoService, (s) => s.completedCount);
  const filter = useServiceState(TodoService, (s) => s.filter);

  if (totalCount === 0) return null;

  return (
    <footer className={styles.footer}>
      <span className={styles.count}>
        <strong>{activeCount}</strong> 项未完成
      </span>
      <nav className={styles.filters} aria-label="筛选">
        {FILTERS.map((f) => (
          <button
            key={f.value}
            className={`${styles.filterBtn} ${filter === f.value ? styles.active : ""}`}
            onClick={() => todo.setFilter(f.value)}
          >
            {f.label}
          </button>
        ))}
      </nav>
      {completedCount > 0 && (
        <button className={styles.clearBtn} onClick={() => todo.clearCompleted()}>
          清除已完成 ({completedCount})
        </button>
      )}
    </footer>
  );
}

// examples/vue-todo/src/components/TodoFooter.vue
<script setup lang="ts">
import { useService } from "@separa/vue";
import { TodoService, type TodoFilter } from "@separa/example-todo-shared";

/**
 * TodoFooter — 展示统计信息、筛选按钮与清除已完成操作。
 * 解构为顶层 Ref 后，模板中 totalCount、activeCount、completedCount、filter 均自动解包。
 */
const { totalCount, activeCount, completedCount, filter, setFilter, clearCompleted } =
  useService(TodoService);

const FILTERS: { label: string; value: TodoFilter }[] = [
  { label: "全部", value: "all" },
  { label: "待完成", value: "active" },
  { label: "已完成", value: "completed" },
];
</script>

<template>
  <footer v-if="totalCount > 0" class="footer">
    <span class="count">
      <strong>{{ activeCount }}</strong> 项未完成
    </span>
    <nav class="filters" aria-label="筛选">
      <button
        v-for="f in FILTERS"
        :key="f.value"
        class="filter-btn"
        :class="{ active: filter === f.value }"
        @click="setFilter(f.value)"
      >
        {{ f.label }}
      </button>
    </nav>
    <button
      v-if="completedCount > 0"
      class="clear-btn"
      @click="clearCompleted()"
    >
      清除已完成 ({{ completedCount }})
    </button>
  </footer>
</template>

<style scoped>
.footer {
  display: flex;
  align-items: center;
  justify-content: space-between;
  flex-wrap: wrap;
  gap: 8px;
  padding: 10px 16px;
  border-top: 1px solid #ededed;
  font-size: 0.85rem;
  color: #777;
  background: #fafafa;
}

.count {
  min-width: 80px;
}

.count strong {
  font-weight: 600;
  color: #555;
}

.filters {
  display: flex;
  gap: 4px;
}

.filter-btn {
  padding: 4px 10px;
  background: none;
  border: 1px solid transparent;
  border-radius: 4px;
  cursor: pointer;
  font-size: 0.83rem;
  color: inherit;
  transition: border-color 0.15s, color 0.15s;
}

.filter-btn:hover {
  border-color: #ccc;
}

.filter-btn.active {
  border-color: #42b883;
  color: #42b883;
}

.clear-btn {
  background: none;
  border: none;
  cursor: pointer;
  font-size: 0.83rem;
  color: #aaa;
  transition: color 0.15s;
  white-space: nowrap;
}

.clear-btn:hover {
  color: #42b883;
}
</style>
