// examples/react-cart/src/App.tsx
import React from "react";
import { SeparaProvider, useService } from "@separa/react";
import { CartStoreService } from "@separa/example-cart-shared";
import { GlobalHeader } from "./components/GlobalHeader";
import { CartItemRow } from "./components/CartItemRow";
import { CartSummary } from "./components/CartSummary";
import "./App.css";

export default function App() {
  const cartStore = useService(CartStoreService);

  function handleAddNewItem() {
    const id = `item-${Date.now().toString().slice(-4)}`;
    cartStore.addItem({
      id,
      name: `新增订制商品 #${id}`,
      price: Math.floor(Math.random() * 2000) + 100,
      quantity: 1,
      category: "自定义配件",
      image: "🎁",
    });
  }

  return (
    <div className="cart-app">
      {/* 顶部全局控制栏 (Parent Scope) */}
      <GlobalHeader />

      <div className="cart-layout">
        {/* 商品列表卡片 */}
        <main className="items-card">
          <div className="items-header">
            <button
              className="select-all-btn"
              onClick={() => cartStore.toggleSelectAll()}
            >
              <input
                type="checkbox"
                className="item-checkbox"
                checked={
                  cartStore.itemScopes.length > 0 &&
                  cartStore.selectedScopes.length === cartStore.itemScopes.length
                }
                readOnly
              />
              <span>全选 ({cartStore.selectedScopes.length}/{cartStore.itemScopes.length})</span>
            </button>
            <button
              className="control-select"
              style={{ padding: "6px 12px", background: "#e0e7ff", color: "#4338ca", border: "none" }}
              onClick={handleAddNewItem}
            >
              + 动态增加商品 (创建子容器)
            </button>
          </div>

          <div className="items-list">
            {cartStore.itemScopes.length === 0 ? (
              <div style={{ padding: "40px", textAlign: "center", color: "#94a3b8" }}>
                购物车空空如也，点击上方按钮新增商品
              </div>
            ) : (
              cartStore.itemScopes.map((scopeEntry) => {
                const childContainer = cartStore.getChildContainer(scopeEntry.id);
                if (!childContainer) return null;
                return (
                  // 💡 关键：为每个商品行注入其独立的子容器 (Child Scope)
                  <SeparaProvider key={scopeEntry.id} container={childContainer}>
                    <CartItemRow onRemove={(id) => cartStore.removeItem(id)} />
                  </SeparaProvider>
                );
              })
            )}
          </div>
        </main>

        {/* 结算侧边栏 */}
        <CartSummary />
      </div>
    </div>
  );
}

// examples/vue-cart/src/App.vue
<script setup lang="ts">
import { useService } from "@separa/vue";
import { CartStoreService } from "@separa/example-cart-shared";
import GlobalHeader from "./components/GlobalHeader.vue";
import CartItemRow from "./components/CartItemRow.vue";
import CartSummary from "./components/CartSummary.vue";
import ScopedItemProvider from "./components/ScopedItemProvider.vue";
import "./App.css";

const cartStore = useService(CartStoreService);

const { itemScopes, selectedScopes, toggleSelectAll, addItem, removeItem } = cartStore;

function handleAddNewItem() {
  const id = `item-${Date.now().toString().slice(-4)}`;
  addItem({
    id,
    name: `新增订制商品 #${id}`,
    price: Math.floor(Math.random() * 2000) + 100,
    quantity: 1,
    category: "自定义配件",
    image: "🎁",
  });
}
</script>

<template>
  <div class="cart-app">
    <!-- 顶部全局控制栏 (Parent Scope) -->
    <GlobalHeader />

    <div class="cart-layout">
      <!-- 商品列表卡片 -->
      <main class="items-card">
        <div class="items-header">
          <button class="select-all-btn" @click="toggleSelectAll()">
            <input
              type="checkbox"
              class="item-checkbox"
              :checked="
                itemScopes.length > 0 &&
                selectedScopes.length === itemScopes.length
              "
              readonly
            />
            <span>全选 ({{ selectedScopes.length }}/{{ itemScopes.length }})</span>
          </button>
          <button
            class="control-select"
            style="padding: 6px 12px; background: #ecfdf5; color: #047857; border: none"
            @click="handleAddNewItem"
          >
            + 动态增加商品 (创建子容器)
          </button>
        </div>

        <div class="items-list">
          <div
            v-if="itemScopes.length === 0"
            style="padding: 40px; text-align: center; color: #94a3b8"
          >
            购物车空空如也，点击上方按钮新增商品
          </div>
          <template v-else>
            <!-- 💡 关键：通过 ScopedItemProvider 为每个商品行绑定其独立的子容器 (Child Scope) -->
            <template
              v-for="scopeEntry in itemScopes"
              :key="scopeEntry.id"
            >
              <ScopedItemProvider
                v-if="cartStore.getChildContainer(scopeEntry.id)"
                :container="cartStore.getChildContainer(scopeEntry.id)!"
              >
                <CartItemRow :on-remove="(id) => removeItem(id)" />
              </ScopedItemProvider>
            </template>
          </template>
        </div>
      </main>

      <!-- 结算侧边栏 -->
      <CartSummary />
    </div>
  </div>
</template>
