// examples/vue-ballcraft/src/components/Ball.vue
<script setup lang="ts">
import { computed } from "vue";
import { PALETTE, type ColorId } from "@separa/example-ballcraft-shared";

const props = withDefaults(
  defineProps<{
    color: ColorId;
    isFloating?: boolean;
  }>(),
  {
    isFloating: false,
  },
);

const backgroundColor = computed(() => PALETTE[props.color] || "#ccc");
</script>

<template>
  <div
    class="ball"
    :class="{ floating: isFloating }"
    :style="{ backgroundColor }"
  />
</template>

// examples/react-ballcraft/src/components/Ball.tsx
import React from "react";
import { PALETTE, type ColorId } from "@separa/example-ballcraft-shared";

interface BallProps {
  color: ColorId;
  isFloating?: boolean;
}

export function Ball({ color, isFloating = false }: BallProps) {
  const bg = PALETTE[color] || "#ccc";
  return (
    <div
      className={`ball ${isFloating ? "floating" : ""}`}
      style={{ backgroundColor: bg }}
    />
  );
}
